pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Info') {
            steps {
                bat 'docker version'
            }
        }

        stage('Docker Build') {
            steps {
                dir('client') {
                    bat 'docker build -t coreinventory-frontend:jenkins .'
                }
            }
        }

        stage('Frontend Info') {
            steps {
                dir('client') {
                    bat 'node --version'
                    bat 'npm --version'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('client') {
                    bat 'npm install'
                }
            }
        }

        stage('Lint') {
            steps {
                dir('client') {
                    bat 'npm run lint'
                }
            }
        }

        stage('Build') {
            steps {
                dir('client') {
                    bat 'npm run build'
                }
            }
        }
    }

    post {
        success {
            echo 'Frontend pipeline completed successfully!'
        }

        failure {
            echo 'Frontend pipeline failed.'
        }
    }
}